component: cls
name: clsDemo

inputs:
  name: serverless-test
  topic: serverless-test
  region: ap-guangzhou
  period: 7
  indexRule:
    # 全文索引配置
    fullText:
      # 大小写是否敏感
      caseSensitive: true
      # 全文分词符
      tokenizer: "@&()='\",;:<>[]{}/ \n\t\r"
    # 键值索引
    keyValue:
      # 大小写是否敏感
      caseSensitive: true
      # 键列表
      keys:
        - key: SCF_RequestId
          type: text
          sqlFlag: true
        - key: SCF_MemUsage
          type: double
          sqlFlag: true
  dashboards:
    - name: example-dashboard
      charts:
        - title: log-count-table
          query: '* | select histogram( cast(__TIMESTAMP__ as timestamp),interval 1 minute) as analytic_time, count(*) as log_count group by analytic_time order by analytic_time limit 1000'
          type: 'table'
        - title: log-count-graph
          query: '* | select histogram( cast(__TIMESTAMP__ as timestamp),interval 1 minute) as analytic_time, count(*) as log_count group by analytic_time order by analytic_time limit 1000'
          type: 'graph'
        - title: log-count-bar
          query: '* | select histogram( cast(__TIMESTAMP__ as timestamp),interval 1 minute) as analytic_time, count(*) as log_count group by analytic_time order by analytic_time limit 1000'
          type: 'bar'
        - title: log-count-stat
          query: '* | select count(*) as log_count'
          type: 'stat'
        - title: log-count-gauge
          query: '* | select count(*) as log_count'
          type: 'gauge'
        - title: log-count-pie
          query: '* | select histogram( cast(__TIMESTAMP__ as timestamp),interval 1 minute) as analytic_time, count(*) as log_count group by analytic_time order by analytic_time limit 1000'
          type: 'pie'
  # alarms:
  #   - name: error-count # 告警名称
  #     # 通知模板 ID
  #     noticeId: notice-xxx
  #     targets: # 监控规则
  #       - period: 15 # 查询时间范围，单位为分钟，默认为15分钟
  #         query: '* | select count(*) as count' # 分析语句
  #     monitor: # 监控周期
  #       type: Period # 固定频率
  #       time: 1 # 每隔多少分钟查询一次
  #       # type: Fixed # 固定时间
  #       # time: 601 # 每天 10:00 执行
  #     trigger: # 告警策略
  #       condition: '$1.count > 1' # 告警频率
  #       count: 1 # 告警频率
  #       period: 10 # 如果持续指定 count，则每 10 分钟告警一次
